
//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using Soneta.Types;
using Soneta.Business;
using Soneta.Examples.EnovaDB;

[assembly: ModuleType("EnovaDB", typeof(Soneta.Examples.EnovaDB.EnovaDBModule), 2, "EnovaDB", 0, VersionNumber=1)]

namespace Soneta.Examples.EnovaDB {

	/// <summary>
	/// Modu³ EnovaDB.
	/// </summary>
	/// <seealso cref="Soneta.Business.Module"/>
	/// <seealso cref="Soneta.Business.Session"/>
	[System.CodeDom.Compiler.GeneratedCode("Soneta.Generator", "2")]
	public partial class EnovaDBModule : Module {

		public static EnovaDBModule GetInstance(ISessionable session) {
			if (session == null || session.Session == null) return null;
			return (EnovaDBModule)session.Session.Modules[typeof(EnovaDBModule)];
		}

		/// <summary>
		/// Standardowy kontruktor modu³u sesji.
		/// </summary>
		/// <param name="session">Sesja w której jest tworzony ten modu³.</param>
		public EnovaDBModule(Session session) : base(session, "EnovaDB") {
			Initialize();
		}

	}
}

