
//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using Soneta.Types;
using Soneta.Business;
using Soneta.Examples.EnovaDB.Punktacja;

[assembly: ModuleType("Punktacja", typeof(Soneta.Examples.EnovaDB.Punktacja.PunktacjaModule), 2, "Punktacja", 0, VersionNumber=1)]

namespace Soneta.Examples.EnovaDB.Punktacja {

	/// <summary>
	/// Modu³ Punktacja.
	/// </summary>
	/// <seealso cref="Soneta.Business.Module"/>
	/// <seealso cref="Soneta.Business.Session"/>
	[System.CodeDom.Compiler.GeneratedCode("Soneta.Generator", "2")]
	public partial class PunktacjaModule : Module {

		public static PunktacjaModule GetInstance(ISessionable session) {
			if (session == null || session.Session == null) return null;
			return (PunktacjaModule)session.Session.Modules[typeof(PunktacjaModule)];
		}

		/// <summary>
		/// Standardowy kontruktor modu³u sesji.
		/// </summary>
		/// <param name="session">Sesja w której jest tworzony ten modu³.</param>
		public PunktacjaModule(Session session) : base(session, "Punktacja") {
			Initialize();
		}

	}
}

